import Head from "next/head";
import styles from "../styles/pages/Home.module.scss";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Link from "next/link";

const Home = () => {
  return (
    <>
      <Head>
        <title>В|S Quest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.app}>
        <Header />
        <main>
          <section className={styles.home}>
            <div className={styles.home__container}>
              <button className={styles.btn}>
                <Link href="/game">
                  <a>Играть</a>
                </Link>
              </button>
            </div>
          </section>
        </main>
        <Footer />
      </div>
    </>
  );
};

export default Home;
